# Generated by Django 2.0 on 2018-11-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadCounter',
            new_name='ReadDetail',
        ),
    ]
