# Generated by Django 2.0 on 2018-05-14 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_counter', '0003_auto_20180514_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name_plural': '阅读详情'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name_plural': '阅读数'},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
