# Generated by Django 2.0 on 2018-05-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='like_time',
            new_name='like_date',
        ),
    ]
