# Generated by Django 2.0 on 2018-05-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180512_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time', '-last_updated_time']},
        ),
    ]
