# Generated by Django 2.0 on 2018-05-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180514_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time', '-last_updated_time'], 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='blogtype',
            options={'verbose_name_plural': '博文类型'},
        ),
    ]
