# Generated by Django 2.0 on 2018-05-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20180520_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time'], 'verbose_name_plural': '评论'},
        ),
    ]
