# Generated by Django 2.0 on 2018-12-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=12)),
                ('link_address', models.CharField(max_length=50)),
                ('link_mark', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'ordering': ['-add_time'],
            },
        ),
    ]
